export const CHANGE_HOME_VIEW   = "CHANGE_HOME_VIEW";
export const CHANGE_DISHES_VIEW = "CHANGE_DISHES_VIEW";
export const CHANGE_PRICES_VIEW = "CHANGE_PRICES_VIEW";
export const CHANGE_IGREDIENTS_VIEW = "CHANGE_IGREDIENTS_VIEW";
export const CHANGE_MENU_VIEW = "CHANGE_MENU_VIEW";
