spring:
  application:
    name: marco-menu-service
server:
  servlet:
    context-path: /menus
    
# I am telling at spring boot where is the eureka server
eureka:
  client:
    serviceUrl:
      #try the value from the system props, or get the fall back
      defaultZone: ${IXICO_EUREKA_SERVER:http://localhost:8090/eureka}
