spring:
  application:
    name: marco-prices-service
server:
  servlet:
    context-path: /prices
    
# I am telling at spring boot where is the eureka server
eureka:
  client:
    serviceUrl:
      #try the value from the system props, or get the fall back
      defaultZone: ${MARCO_EUREKA_SERVER:http://192.168.99.102:8761/eureka}
