version: "3.7"
services:
  mongodb:
    image: marco/mongodb
    build:
      dockerfile: Dockerfile
      context: ./mongodb
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
  postgres:
    image: marco/postgres
    build:
      dockerfile: Dockerfile
      context: ./postgres
    ports:
      - "5432:5432"