version: "3.7"

networks:
  marco:
    name: marco_network

services:
  mongodb:
    image: marco/mongodb
    networks:
     - marco
    build:
      dockerfile: Dockerfile
      context: ./mongodb
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
  marco-db:
    image: marco/postgres
    networks:
       - marco
    build:
      dockerfile: Dockerfile
      context: ./postgres
    ports:
      - "5432:5432"
  keycloack:
    image: marco/keycloak
    networks:
     - marco
    build:
      dockerfile: Dockerfile
      context: ./keycloak
    ports:
      - "8091:8080"
    environment:
       - KEYCLOAK_USER=admin
       - KEYCLOAK_PASSWORD=password
       - DB_VENDOR=postgres
       - DB_USER=postgres
       - DB_PASSWORD=postgres
       - DB_ADDR=marco-db
    depends_on:
       - marco-db
       

      