server:
  port: 8086
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reactui
      repositories:
        type: auto
        
        
        
keycloak:
  realm: marco-realm # the name of the realm, required;
  resource: marco-react-ui # the client-id of the application, required;
  auth-server-url: http://localhost:8091/auth # the base URL of the Keycloak server, required;
  ssl-required: external # stablishes if communications with the Keycloak server must happen over HTTPS. Here, it's set to external, meaning that it's only needed for external requests (default value). In production, instead, we should set it to all. Optional;
  public-client: true # prevents the application from sending credentials to the Keycloak server (false is the default value). We want to set it to true whenever we use public clients instead of confidential. Optional;
  principal-attribute: preferred_username # the attribute with which to populate the UserPrincipal name. Optional.
        
#############################
# Properties used when need to call the other services
#############################      
rest:
  request:
    service:
      dishes:
        protocol: https
        host: marco-dishes-service
        findDishByName: /dishes/api
        findAllDishes: /dishes/api/all
        deleteDish: /dishes/api
        insertDish: /dishes/api
        updateDish: /dishes/api
      prices:
        protocol: https
        host: marco-prices-service
        findPriceByName: /prices/api
        findAllPrices: /prices/api/all
        deletePrice: /prices/api
        insertPrice: /prices/api
        updatePrice: /prices/api
      ingredients:
        protocol: https 
        host: marco-ingredients-service
        findRecipeByDishName: /ingredients/api
        findAllRecipes: /ingredients/api/all
        deleteRecipe: /ingredients/api
        insertRecipe: /ingredients/api
      menus:
        protocol: https 
        host: marco-menu-service
        findMenuByName: /menus/api
        findAllMenus: /menus/api/all
        deleteMenu: /menus/api
        insertMenu: /menus/api 
        
