server:
  port: 8086
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reactui
      repositories:
        type: auto
        
        
rest:
  request:
    service:
      dishes:
        protocol: https
        host: marco-dishes-service
        findDishByName: /dishes/api
        findAllDishes: /dishes/api/all
        deleteDish: /dishes/api
        insertDish: /dishes/api
        updateDish: /dishes/api
      prices:
        protocol: https
        host: marco-prices-service
        findPriceByName: /prices/api
        findAllPrices: /prices/api/all
        deletePrice: /prices/api
        insertPrice: /prices/api
        updatePrice: /prices/api