CREATE DATABASE KEYCLOAK;


CREATE DATABASE RESTOURANTMENU;

\c restourantmenu

CREATE TABLE DISHES(
NAME		VARCHAR(50) NOT NULL DEFAULT '',
CALORIES	INTEGER		NOT NULL DEFAULT 0,
PRIMARY KEY (NAME)
);

CREATE TABLE INGREDIENTS(
DISH_NAME		VARCHAR(50) NOT NULL DEFAULT '',
INGREDIENT_NAME	TEXT		NOT NULL DEFAULT '',
PRIMARY KEY (DISH_NAME, INGREDIENT_NAME)
);

CREATE TABLE MENUS(
MENU_NAME	VARCHAR(50) NOT NULL DEFAULT '',
DISH_NAME	VARCHAR(50) NOT NULL DEFAULT '',
PRIMARY KEY (MENU_NAME, DISH_NAME)
);

CREATE TABLE PRICES(
DISH_NAME	VARCHAR(50) NOT NULL DEFAULT '',
PRICE		INTEGER		NOT NULL DEFAULT 0,
PRIMARY KEY (DISH_NAME)
);