spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marcosolina/microservicespoc.git #Repository that hosts the properties
          default-label: ${GIT_REPO_BRANCH:security_tests}
          search-paths: #list of folders to use when retrieving the properties
          - 'appProperties/dishesService/'
          - 'appProperties/ingredientsProperties/'
          - 'appProperties/pricesService/'
          - 'appProperties/menuService/'
          - 'appProperties/reactUi/'
          

server:
  port: 8888 #Port to use when running this service
  # I am telling at spring boot where is the eureka server
eureka:
  client:
    serviceUrl:
      #try the value from the system props, or get the fall back
      defaultZone: ${MARCO_EUREKA_SERVER:http://192.168.99.102:8761/eureka}
