spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marcosolina/microservicespoc.git
          search-paths:
          - 'appProperties/dishesService/'
          - 'appProperties/ingredientsProperties/'
          - 'appProperties/pricesService/'
          - 'appProperties/menuService/'
          

server:
  port: 8888
  # I am telling at spring boot where is the eureka server
eureka:
  client:
    serviceUrl:
      #try the value from the system props, or get the fall back
      defaultZone: ${MARCO_EUREKA_SERVER:http://localhost:8090/eureka}
