server:
  port: 8083
  
# Where to go to check the incoming token
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.99.102:8091/auth/realms/marco-realm/protocol/openid-connect/certs    
  
rest:
  request:
    service:
      dishes:
        protocol: https
        host: marco-dishes-service
        findDishByName: /dishes/api
        findAllDishes: /dishes/api/all